name: Conditional Sync Build

on:
  schedule:
    - cron: '0 * * * *' # ogni ora
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync upstream (no force)
        id: sync
        run: |
          set -ex

          git remote get-url upstream || git remote add upstream https://github.com/UrloMythus/MammaMia.git
          git fetch upstream

          if git diff --quiet HEAD upstream/main; then
            echo "Repository already up to date"
            echo "no_change=true" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, merging..."

            git merge upstream/main --no-edit

            git push origin main

            echo "no_change=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if something changed
        if: steps.sync.outputs.no_change == 'false'
        run: echo "Repository updated successfully."
